[package]
name = "system-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4"
anyhow = "1.0"
debugrs = "0.2.1"
dotenv = "0.15.0"
serde_json = "1.0.135"
serde = { version = "1.0.217", features = ["derive"] }
sysinfo = "0.34.2"